//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estudo.LinqEF.ExemploEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Compras = new HashSet<Compras>();
        }
    
        public int ClienteId { get; set; }
        public string Nome { get; set; }
    
        public virtual ICollection<Compras> Compras { get; set; }
    }
}
