//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estudo.LinqEF.ExemploEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        public int CompraId { get; set; }
        public System.DateTime DataCompra { get; set; }
        public decimal Valor { get; set; }
        public int ClienteClienteId { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
