// <auto-generated />
namespace Estudo.LinqEF.ExemploEntity.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AlteracaoFucnionario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlteracaoFucnionario));
        
        string IMigrationMetadata.Id
        {
            get { return "201810291132064_AlteracaoFucnionario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
